apiVersion: intersystems.com/v1alpha1
kind: IrisCluster
metadata:
  name: irismirror
spec:
  passwordHash: '8bd95768a1c67cc44f425d69cee553cdb442367c,orppc7ok'
  licenseKeySecret:
    name: iris-key-secret
  configSource:
    name: iris-cpf
  topology:
    arbiter:
      image: containers.intersystems.com/intersystems/arbiter:2020.4.0.521.0
      podTemplate:
        spec:
          imagePullSecrets:
            - name: dockerhub-secret 
    data:
      mirrored: true
      image: containers.intersystems.com/intersystems/irishealth:2020.2.0.211.0
      podTemplate:
        spec:
          imagePullSecrets:
            - name: dockerhub-secret
      updateStrategy:
        type: RollingUpdate
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10G
        storageClassName: hostpath
    
